# Generated by Django 2.0.1 on 2018-03-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20180309_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='user',
            new_name='customer',
        ),
    ]
